// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCkdZZcFrKP3VvwrEkTTqD4H71o7LNRu4',
    appId: '1:841258257364:web:b62b3ff8907448d414a441',
    messagingSenderId: '841258257364',
    projectId: 'tistoryflutter2407',
    authDomain: 'tistoryflutter2407.firebaseapp.com',
    storageBucket: 'tistoryflutter2407.appspot.com',
    measurementId: 'G-Y88NNY08GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXidxH2t6FCfz_RiiwM_rH9WlABH9ZEU',
    appId: '1:841258257364:android:6f1390e566f7e83d14a441',
    messagingSenderId: '841258257364',
    projectId: 'tistoryflutter2407',
    storageBucket: 'tistoryflutter2407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa2t3B6VWy-c50tgLS1sIxUIc-lKy06Oc',
    appId: '1:841258257364:ios:b32bb0b4cf24cd6a14a441',
    messagingSenderId: '841258257364',
    projectId: 'tistoryflutter2407',
    storageBucket: 'tistoryflutter2407.appspot.com',
    iosBundleId: 'tistory.glorygem.firebaseauth.firebaseAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa2t3B6VWy-c50tgLS1sIxUIc-lKy06Oc',
    appId: '1:841258257364:ios:b32bb0b4cf24cd6a14a441',
    messagingSenderId: '841258257364',
    projectId: 'tistoryflutter2407',
    storageBucket: 'tistoryflutter2407.appspot.com',
    iosBundleId: 'tistory.glorygem.firebaseauth.firebaseAuthProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCkdZZcFrKP3VvwrEkTTqD4H71o7LNRu4',
    appId: '1:841258257364:web:e2ffbbc0788dc9f814a441',
    messagingSenderId: '841258257364',
    projectId: 'tistoryflutter2407',
    authDomain: 'tistoryflutter2407.firebaseapp.com',
    storageBucket: 'tistoryflutter2407.appspot.com',
    measurementId: 'G-8VD0EBFHKZ',
  );
}
